/** Simple Icons slug per https://simpleicons.org/ — used with cdn.simpleicons.org */
export const TECH_SLUGS: Record<string, string> = {
  "Next.js": "nextdotjs",
  React: "react",
  Angular: "angular",
  "Vue.js": "vuedotjs",
  "Node.js": "nodedotjs",
  "Express.js": "express",
  TypeScript: "typescript",
  "Tailwind CSS": "tailwindcss",
  GraphQL: "graphql",
  "React Native": "react",
  Flutter: "flutter",
  "Swift (iOS)": "swift",
  "Kotlin (Android)": "kotlin",
  Expo: "expo",
  Ionic: "ionic",
  Python: "python",
  TensorFlow: "tensorflow",
  PyTorch: "pytorch",
  "Scikit-learn": "scikitlearn",
  "Hugging Face": "huggingface",
  LangChain: "langchain",
  "OpenAI GPT": "openai",
  "Anthropic Claude": "anthropic",
  CrewAI: "crewai",
  MLflow: "mlflow",
  CUDA: "nvidia",
  "Pandas / NumPy": "pandas",
  AWS: "amazonaws",
  "Google Cloud": "googlecloud",
  "Microsoft Azure": "microsoftazure",
  Docker: "docker",
  Kubernetes: "kubernetes",
  Terraform: "terraform",
  "GitHub Actions": "githubactions",
  Jenkins: "jenkins",
  Grafana: "grafana",
  Datadog: "datadog",
  Nginx: "nginx",
  Vercel: "vercel",
  PostgreSQL: "postgresql",
  MySQL: "mysql",
  MongoDB: "mongodb",
  Redis: "redis",
  Elasticsearch: "elasticsearch",
  Pinecone: "pinecone",
  ChromaDB: "chroma",
  InfluxDB: "influxdb",
  Supabase: "supabase",
  Firebase: "firebase",
  FastAPI: "fastapi",
  Django: "django",
  Flask: "flask",
  "Spring Boot": "springboot",
  Java: "openjdk",
  ".NET Core": "dotnet",
  "PHP / Laravel": "laravel",
  "Ruby on Rails": "rubyonrails",
  Solidity: "solidity",
  Ethereum: "ethereum",
  Polygon: "polygon",
  Hyperledger: "hyperledger",
  "Web3.js": "web3dotjs",
  Hardhat: "hardhat",
  IPFS: "ipfs",
  "Rust (Solana)": "rust",
  "AWS IoT": "amazonaws",
  "Azure IoT Hub": "microsoftazure",
  MQTT: "mqtt",
  "Node-RED": "nodered",
  "Raspberry Pi": "raspberrypi",
  Arduino: "arduino",
  Figma: "figma",
  "Adobe XD": "adobexd",
  Sketch: "sketch",
  Framer: "framer",
  Storybook: "storybook",
  "Shadcn UI": "shadcnui",
  "Material UI": "mui",
  "Power BI": "powerbi",
  Tableau: "tableau",
  "Apache Spark": "apachespark",
  Snowflake: "snowflake",
  Airflow: "apacheairflow",
  dbt: "dbt",
  Metabase: "metabase",
  Jupyter: "jupyter",
  Jest: "jest",
  Cypress: "cypress",
  Playwright: "playwright",
  Selenium: "selenium",
  JMeter: "apachejmeter",
  Postman: "postman",
  SonarQube: "sonarqube",
  k6: "k6",
  Cloudflare: "cloudflare",
  Vault: "hashicorp",
  "REST APIs": "json",
  WebSocket: "socketdotio",
  Microservices: "kubernetes",
  Serverless: "serverless",
  LoRaWAN: "lora",
  Zigbee: "zigbee",
  OWASP: "owasp",
  "OAuth 2.0 / JWT": "jwt",
  "SSL / TLS": "openssl",
};

/** Optional brand hex for cdn.simpleicons.org/[slug]/[color] */
export const TECH_COLORS: Record<string, string> = {
  "Next.js": "000000",
  React: "61DAFB",
  Angular: "DD0031",
  "Vue.js": "4FC08D",
  "Node.js": "339933",
  TypeScript: "3178C6",
  AWS: "FF9900",
  "Google Cloud": "4285F4",
  "Microsoft Azure": "0078D4",
  Docker: "2496ED",
  Kubernetes: "326CE5",
  Terraform: "7B42BC",
  Vercel: "000000",
  Python: "3776AB",
  "OpenAI GPT": "412991",
};
